/*
	SlimeVR Code is placed under the MIT license
	Copyright (c) 2024 Eiren Rain & SlimeVR contributors

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
*/
#ifndef SENSOR_POSITION_H
#define SENSOR_POSITION_H

#define POSITION_NO 0
#define POSITION_HEAD 1
#define POSITION_NECK 2
#define POSITION_UPPER_CHEST 3
#define POSITION_CHEST 4
#define POSITION_WAIST 5
#define POSITION_HIP 6
#define POSITION_LEFT_UPPER_LEG 7
#define POSITION_RIGHT_UPPER_LEG 8
#define POSITION_LEFT_LOWER_LEG 9
#define POSITION_RIGHT_LOWER_LEG 10
#define POSITION_LEFT_FOOT 11
#define POSITION_RIGHT_FOOT 12
#define POSITION_LEFT_LOWER_ARM 13
#define POSITION_RIGHT_LOWER_ARM 14
#define POSITION_LEFT_UPPER_ARM 15
#define POSITION_RIGHT_UPPER_ARM 16
#define POSITION_LEFT_HAND 17
#define POSITION_RIGHT_HAND 18
#define POSITION_LEFT_SHOULDER 19
#define POSITION_RIGHT_SHOULDER 20
#define POSITION_LEFT_THUMB_METACARPAL 21
#define POSITION_LEFT_THUMB_PROXIMAL 22
#define POSITION_LEFT_THUMB_DISTAL 23
#define POSITION_LEFT_INDEX_PROXIMAL 24
#define POSITION_LEFT_INDEX_INTERMEDIATE 25
#define POSITION_LEFT_INDEX_DISTAL 26
#define POSITION_LEFT_MIDDLE_PROXIMAL 27
#define POSITION_LEFT_MIDDLE_INTERMEDIATE 28
#define POSITION_LEFT_MIDDLE_DISTAL 29
#define POSITION_LEFT_RING_PROXIMAL 30
#define POSITION_LEFT_RING_INTERMEDIATE 31
#define POSITION_LEFT_RING_DISTAL 32
#define POSITION_LEFT_LITTLE_PROXIMAL 33
#define POSITION_LEFT_LITTLE_INTERMEDIATE 34
#define POSITION_LEFT_LITTLE_DISTAL 35
#define POSITION_RIGHT_THUMB_METACARPAL 36
#define POSITION_RIGHT_THUMB_PROXIMAL 37
#define POSITION_RIGHT_THUMB_DISTAL 38
#define POSITION_RIGHT_INDEX_PROXIMAL 39
#define POSITION_RIGHT_INDEX_INTERMEDIATE 40
#define POSITION_RIGHT_INDEX_DISTAL 41
#define POSITION_RIGHT_MIDDLE_PROXIMAL 42
#define POSITION_RIGHT_MIDDLE_INTERMEDIATE 43
#define POSITION_RIGHT_MIDDLE_DISTAL 44
#define POSITION_RIGHT_RING_PROXIMAL 45
#define POSITION_RIGHT_RING_INTERMEDIATE 46
#define POSITION_RIGHT_RING_DISTAL 47
#define POSITION_RIGHT_LITTLE_PROXIMAL 48
#define POSITION_RIGHT_LITTLE_INTERMEDIATE 49
#define POSITION_RIGHT_LITTLE_DISTAL 50

#define GLOVE_LEFT 1
#define GLOVE_RIGHT 2

#endif
