#ifndef SLIMEVR_CALIBRATION_H_
#define SLIMEVR_CALIBRATION_H_

#define CALIBRATION_TYPE_INTERNAL_GYRO 1
#define CALIBRATION_TYPE_INTERNAL_ACCEL 2
#define CALIBRATION_TYPE_INTERNAL_MAG 3
#define CALIBRATION_TYPE_EXTERNAL_ALL 4
#define CALIBRATION_TYPE_EXTERNAL_GYRO 5
#define CALIBRATION_TYPE_EXTERNAL_ACCEL 6
#define CALIBRATION_TYPE_EXTERNAL_MAG 7

#endif // SLIMEVR_CALIBRATION_H_